[Monocolor]
kind = "mana-pool"
color-identity-len = 1

["Dual-Color"]
kind = "mana-pool"
color-identity-len = 2

["Tri-Color"]
kind = "mana-pool"
color-identity-len = 3

["Any Color"]
kind = "mana-pool"
text = '(any( combination of| one)? colors?|mana of (that color|any type)|mana of different colors)'

["Commander Color"]
kind = "mana-pool"
text = "any color in your commander's color identity"

[Colorless]
kind = "color-identity"
color-identity = []

[White]
kind = "color-identity"
color-identity = ["W"]

[Blue]
kind = "color-identity"
color-identity = ["U"]

[Black]
kind = "color-identity"
color-identity = ["B"]

[Red]
kind = "color-identity"
color-identity = ["R"]

[Green]
kind = "color-identity"
color-identity = ["G"]

[Azorius]
kind = "color-identity"
color-identity = ["W", "U"]

[Selesnya]
kind = "color-identity"
color-identity = ["W", "G"]

[Dimir]
kind = "color-identity"
color-identity = ["U", "B"]

[Rakdos]
kind = "color-identity"
color-identity = ["B", "R"]

[Gruul]
kind = "color-identity"
color-identity = ["R", "G"]

[Orzhov]
kind = "color-identity"
color-identity = ["W", "B"]

[Boros]
kind = "color-identity"
color-identity = ["W", "R"]

[Izzet]
kind = "color-identity"
color-identity = ["U", "R"]

[Simic]
kind = "color-identity"
color-identity = ["U", "G"]

[Golgari]
kind = "color-identity"
color-identity = ["B", "G"]

[Esper]
kind = "color-identity"
color-identity = ["W", "U", "B"]

[Bant]
kind = "color-identity"
color-identity = ["W", "U", "G"]

[Naya]
kind = "color-identity"
color-identity = ["W", "R", "G"]

[Grixis]
kind = "color-identity"
color-identity = ["U", "B", "R"]

[Jund]
kind = "color-identity"
color-identity = ["B", "R", "G"]

[Jeskai]
kind = "color-identity"
color-identity = ["W", "U", "R"]

[Mardu]
kind = "color-identity"
color-identity = ["W", "B", "R"]

[Abzan]
kind = "color-identity"
color-identity = ["W", "B", "G"]

[Sultai]
kind = "color-identity"
color-identity = ["U", "B", "G"]

[Temur]
kind = "color-identity"
color-identity = ["U", "R", "G"]

[Domain]
kind = "color-identity"
color-identity = ["W", "U", "B", "R", "G"]

["CMC 0"]
kind = "cost"
cmc = 0
subtags = ["Artifact Lands", "Charge Counters", "One-shot", "Mox"]

["Artifact Lands"]
type = 'Artifact Land'

["Charge Counters"]
text = 'charge counter'

["One-shot"]
names = ["Lion's Eye Diamond", "Lotus Bloom", "Lotus Petal"]

[Mox]
cmc = 0
name = '\bMox\b'

["CMC 1"]
kind = 'cost'
cmc = 1
subtags = ["Eggs"]

[Eggs]
names = ["Barbed Sextant", "Chromatic Sphere", "Chromatic Star", "Darkwater Egg", "Mossfire Egg",
    "Shadowblood Egg", "Skycloud Egg", "Sungrass Egg", "Terrarion"]