name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_RELEASE_DEBUG: 0

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build generator
        run: cargo build --release --verbose
        env:
          RUSTFLAGS: -C target-cpu=native
      - name: Run generator
        run: cargo run --release
        env:
          RUST_LOG: info
          RUSTFLAGS: -C target-cpu=native
      - name: Deploy GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_branch: gh-pages
          jekyll: false
          # Create incremental commit instead of doing push force
          keep_history: true
          # Allow an empty commit to be created
          allow_empty_commit: false
          # Build directory to deploy
          build_dir: target/www
